name: Terraform Apply

on:
  push:
    branches: [main, master]
  workflow_call:
    inputs:
      tf_workspace:
        required: true
        type: string
      aws_region:
        required: false
        type: string
        default: "ap-southeast-2"
      gh_repo:
        type: string
        required: true
      databricks_account_id:
        type: string
        required: false
      target_role_arn:
        type: string
        required: true
      tag:
        required: true
        type: string
      tf_dir:
        required: true
        type: string
      tf_file:
        required: true
        type: string
      cloud:
        required: true
        type: string
      workspace_s3_bucket_name:
        required: false
        type: string
      databricks_relay_endpoint_id:
        required: false
        type: string
      databricks_workspace_endpoint_id:
        required: false
        type: string
      databricks_workspace_id:
        required: false
        type: string
      databricks_workspace_url:
        required: false
        type: string
      azure_client_id:
        required: false
        type: string
      azure_sub_id:
        required: false
        type : string
      azure_tenant_id:
        required: false
        type: string
      storage_account_name:
        required: false
        type: string
      vnet_id:
        required: false
        type: string
      subnet_id:
        required: false
        type: string

    secrets:
      RIOTINTO_ORG_TOKEN:
        required: true
      CUSTOM_GITHUB_TOKEN:
        required: false
      databricks_client_id:
        required: false
      databricks_client_secret:
        required: false

    outputs:
      aws_databricks_workspace_id:
        description: "AWS Databricks id"
        value: ${{ jobs.aws-terraform-apply.outputs.databricks_workspace_id }}
      azure_databricks_workspace_id:
        description: "Azure Databricks id"
        value: ${{ jobs.azure-terraform-apply.outputs.databricks_workspace_id }}
      databricks_workspace_id:
        description: "Databricks workspace id (AWS or Azure)"
        value: ${{ inputs.cloud == 'aws' && jobs.aws-terraform-apply.outputs.databricks_workspace_id || jobs.azure-terraform-apply.outputs.databricks_workspace_id }}
      databricks_workspace_url:
        description: "Databricks workspace URL (AWS or Azure)"
        value: ${{ inputs.cloud == 'aws' && jobs.aws-terraform-apply.outputs.databricks_workspace_url || jobs.azure-terraform-apply.outputs.databricks_workspace_url }}
      # Additional surfaced outputs for downstream jobs
      vnet_id:
        description: "Azure VNet ID"
        value: ${{ jobs.azure-terraform-apply.outputs.vnet_id }}
      subnet_ids:
        description: "Azure Subnet IDs (JSON array/string)"
        value: ${{ jobs.azure-terraform-apply.outputs.subnet_ids }}
      vpc_relay_endpoint_id:
        description: "Private Relay Endpoint ID"
        value: ${{ jobs.azure-terraform-apply.outputs.vpc_relay_endpoint_id }}
      vpc_workspace_endpoint_id:
        description: "Workspace Private Endpoint ID"
        value: ${{ jobs.azure-terraform-apply.outputs.vpc_workspace_endpoint_id }}
      instance_profile_id:
        description: "Instance Profile ID"
        value: ${{ jobs.azure-terraform-apply.outputs.instance_profile_id }}
      catalog_ids:
        description: "Unity Catalog IDs"
        value: ${{ jobs.azure-terraform-apply.outputs.catalog_ids }}
      schema_ids:
        description: "Unity Schema IDs"
        value: ${{ jobs.azure-terraform-apply.outputs.schema_ids }}
      external_location_ids:
        description: "External Location IDs"
        value: ${{ jobs.azure-terraform-apply.outputs.external_location_ids }}
      volume_ids:
        description: "Volume IDs"
        value: ${{ jobs.azure-terraform-apply.outputs.volume_ids }}
      compute_cluster_ids:
        description: "Compute Cluster IDs"
        value: ${{ jobs.azure-terraform-apply.outputs.compute_cluster_ids }}
      sql_warehouse_ids:
        description: "SQL Warehouse IDs"
        value: ${{ jobs.azure-terraform-apply.outputs.sql_warehouse_ids }}
      service_principal_ids:
        description: "Service Principal IDs"
        value: ${{ jobs.azure-terraform-apply.outputs.service_principal_ids }}

permissions:
  contents: read
  id-token: write
  pull-requests: write
  issues: write

jobs:

  aws-terraform-apply:
    if: ${{ inputs.cloud == 'aws' }}
    runs-on: ubuntu-latest

    outputs:
      databricks_workspace_id: ${{ steps.tfApply.outputs.databricks_workspace_id }}
      databricks_workspace_url: ${{ steps.tfApply.outputs.databricks_workspace_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: rio-tinto/${{ inputs.gh_repo }}
          ref: ${{ inputs.tag || github.ref }}

      - name: Configure GitHub credentials
        run: |
          git config --global url."https://${{ secrets.RIOTINTO_ORG_TOKEN }}@github.com/".insteadOf "https://github.com/"
          git config --global url."git@github.com:".insteadOf "https://github.com/"
          git config --list
        working-directory: "${{ inputs.tf_dir }}"

      - name: OIDC Login to AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ inputs.target_role_arn }}
          role-session-name: DNA-Automation-Github-Actions-Role
          aws-region: ${{ inputs.aws_region }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3.1.1

      - name: Initialize Terraform working directory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ${{ inputs.tf_dir }}
          terraform init

      - name: Create or Select Workspace
        run: |
          cd ${{ inputs.tf_dir }}
          WORKSPACE="${{ inputs.tf_workspace }}"
          if terraform workspace list | grep -q "$WORKSPACE"; then
            terraform workspace select $WORKSPACE
          else
            terraform workspace new $WORKSPACE
          fi

      - name: Terraform Apply
        if: ${{ inputs.databricks_account_id != '782ba817-b9bf-4033-9aa9-56bb80139fba' }}
        env:
          TF_VAR_github_token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        run: |
          cd ${{ inputs.tf_dir }}
          if [ -f "tfplan" ]; then
            terraform apply tfplan
          else
            terraform apply -var-file=${{ inputs.tf_file }} -auto-approve
          fi

      - name: Terraform Apply Databricks Workspace
        id: tfApply
        if: ${{ inputs.databricks_account_id == '782ba817-b9bf-4033-9aa9-56bb80139fba' && inputs.tf_dir == 'workspace' }}
        env:
          DATABRICKS_HOST: "https://accounts.cloud.databricks.com"
          DATABRICKS_ACCOUNT_ID: ${{ inputs.databricks_account_id }}
          DATABRICKS_CLIENT_ID: ${{ secrets.databricks_client_id }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.databricks_client_secret }}
        run: |
          cd ${{ inputs.tf_dir }}
          if [ ! -f "tfplan" ]; then
            terraform plan -var-file='${{ inputs.tf_file }}' \
            -var 'databricks_client_id=${{ secrets.databricks_client_id }}' \
            -var 'databricks_client_secret=${{ secrets.databricks_client_secret }}' \
            -var 'databricks_workspace_endpoint_id=${{ inputs.databricks_workspace_endpoint_id }}' \
            -var 'databricks_relay_endpoint_id=${{ inputs.databricks_relay_endpoint_id }}' \
            -out=tfplan
          fi
          if [ -f "tfplan" ]; then
            terraform apply tfplan
          else
            terraform apply -var-file='${{ inputs.tf_file }}' -auto-approve \
            -var 'databricks_client_id=${{ secrets.databricks_client_id }}' \
            -var 'databricks_client_secret=${{ secrets.databricks_client_secret }}' \
            -var 'databricks_workspace_endpoint_id=${{ inputs.databricks_workspace_endpoint_id }}' \
            -var 'databricks_relay_endpoint_id=${{ inputs.databricks_relay_endpoint_id }}'
          fi

          echo "databricks_workspace_id=$(terraform output -raw databricks_workspace_id)" >> $GITHUB_OUTPUT
          echo "databricks_workspace_url=$(terraform output -raw databricks_workspace_url)" >> $GITHUB_OUTPUT

  azure-terraform-apply:
    runs-on: ubuntu-latest
    if: ${{ inputs.cloud == 'az' }}

    outputs:
      databricks_workspace_id: ${{ steps.tf-apply-workspace.outputs.databricks_workspace_id }}
      databricks_workspace_url: ${{ steps.tf-apply-workspace.outputs.databricks_workspace_url }}
      vnet_id: ${{ steps.collect-outputs.outputs.vnet_id }}
      subnet_ids: ${{ steps.collect-outputs.outputs.subnet_ids }}
      vpc_relay_endpoint_id: ${{ steps.collect-outputs.outputs.vpc_relay_endpoint_id }}
      vpc_workspace_endpoint_id: ${{ steps.collect-outputs.outputs.vpc_workspace_endpoint_id }}
      instance_profile_id: ${{ steps.collect-outputs.outputs.instance_profile_id }}
      catalog_ids: ${{ steps.collect-outputs.outputs.catalog_ids }}
      schema_ids: ${{ steps.collect-outputs.outputs.schema_ids }}
      external_location_ids: ${{ steps.collect-outputs.outputs.external_location_ids }}
      volume_ids: ${{ steps.collect-outputs.outputs.volume_ids }}
      compute_cluster_ids: ${{ steps.collect-outputs.outputs.compute_cluster_ids }}
      sql_warehouse_ids: ${{ steps.collect-outputs.outputs.sql_warehouse_ids }}
      service_principal_ids: ${{ steps.collect-outputs.outputs.service_principal_ids }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          repository: rio-tinto/${{ inputs.gh_repo }}
          ref: ${{ inputs.tag || github.ref }}

      - name: Configure GitHub credentials
        run: |
          git config --global url."https://${{ secrets.RIOTINTO_ORG_TOKEN }}@github.com/".insteadOf "https://github.com/"
          git config --global url."git@github.com:".insteadOf "https://github.com/"
          git config --list
        working-directory: "${{ inputs.tf_dir }}"  

      - name: Authenticate to Lakehouse shared account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.target_role_arn }}
          role-session-name: GithubActions-${{ github.event.repository.name }}-${{ github.run_id }}
          aws-region: ${{ inputs.aws_region }}
 
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ inputs.azure_client_id }}
          tenant-id: ${{ inputs.azure_tenant_id }}
          subscription-id: ${{ inputs.azure_sub_id }}

      - name: Azure Account Show
        run: |
          az account show

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3.1.1

      - name: Initialize Terraform working directory
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ${{ inputs.tf_dir }}
          terraform init

      - name: Create or Select Workspace
        run: |
          cd ${{ inputs.tf_dir }}
          WORKSPACE="${{ inputs.tf_workspace }}"
          if terraform workspace list | grep -q "$WORKSPACE"; then
            terraform workspace select $WORKSPACE
          else
            terraform workspace new $WORKSPACE
          fi

      - name: Terraform Apply (Azure Infra)
        if: ${{ !inputs.databricks_account_id }}
        id: tf-apply-azure-infra
        run: |
          cd ${{ inputs.tf_dir }}
          if [ -f "tfplan" ]; then
            terraform apply tfplan
          else
            terraform apply -var-file=${{ inputs.tf_file }} -auto-approve
          fi

      - name: Terraform Apply (Databricks Workspace)
        if: ${{ inputs.databricks_account_id == 'fe1630db-b2af-4ac1-a394-9f0e33096a57' && endsWith(inputs.tf_dir, 'workspace') }}
        id: tf-apply-workspace
        run: |
          cd ${{ inputs.tf_dir }}
          terraform apply -var-file='${{ inputs.tf_file }}' -auto-approve \
          -var 'databricks_account_id=${{ inputs.databricks_account_id }}' \
          -var 'databricks_client_id=${{ secrets.databricks_client_id }}' \
          -var 'databricks_client_secret=${{ secrets.databricks_client_secret }}'

          echo "databricks_workspace_id=$(terraform output -raw workspace_id)" >> $GITHUB_OUTPUT
          echo "databricks_workspace_url=$(terraform output -raw workspace_url)" >> $GITHUB_OUTPUT

      - name: Terraform Apply (Databricks Non-Workspace)
        if: ${{ inputs.databricks_account_id == 'fe1630db-b2af-4ac1-a394-9f0e33096a57' && !endsWith(inputs.tf_dir, 'workspace') }}
        run: |
          cd ${{ inputs.tf_dir }}
          if [[ "${{ inputs.tf_dir }}" == "compute" || "${{ inputs.tf_dir }}" == "catalogs" ]]; then
            terraform apply -var-file='${{ inputs.tf_file }}' -auto-approve \
            -var databricks_workspace_url=${{ inputs.databricks_workspace_url }} \
            -var 'databricks_client_id=${{ secrets.databricks_client_id }}' \
            -var 'databricks_client_secret=${{ secrets.databricks_client_secret }}'
          else
            terraform apply -var-file='${{ inputs.tf_file }}' -auto-approve \
            -var databricks_account_id=${{ inputs.databricks_account_id }} \
            -var databricks_workspace_id=${{ inputs.databricks_workspace_id }} \
            -var databricks_workspace_url=${{ inputs.databricks_workspace_url }} \
            -var 'databricks_client_id=${{ secrets.databricks_client_id }}' \
            -var 'databricks_client_secret=${{ secrets.databricks_client_secret }}'
          fi

      - name: Collect Terraform outputs
        id: collect-outputs
        if: ${{ always() }}
        run: |
          cd ${{ inputs.tf_dir }}
          VNET_ID=$(terraform output -raw vnet_id 2>/dev/null || true)
          SUBNET_IDS=$(terraform output -json subnet_ids 2>/dev/null | jq -c . || true)
          RELAY_EP=$(terraform output -raw vpc_relay_endpoint_id 2>/dev/null || true)
          WS_EP=$(terraform output -raw vpc_workspace_endpoint_id 2>/dev/null || true)
          INSTANCE_PROFILE_ID=$(terraform output -raw instance_profile_id 2>/dev/null || true)
          CATALOG_IDS=$(terraform output -json catalog_ids 2>/dev/null | jq -c . || true)
          SCHEMA_IDS=$(terraform output -json schema_ids 2>/dev/null | jq -c . || true)
          EXT_LOC_IDS=$(terraform output -json external_location_ids 2>/dev/null | jq -c . || true)
          VOLUME_IDS=$(terraform output -json volume_ids 2>/dev/null | jq -c . || true)
          CLUSTER_IDS=$(terraform output -json compute_cluster_ids 2>/dev/null | jq -c . || true)
          SQL_WH_IDS=$(terraform output -json sql_warehouse_ids 2>/dev/null | jq -c . || true)
          SP_IDS=$(terraform output -json service_principal_ids 2>/dev/null | jq -c . || true)
          if [ -n "$VNET_ID" ]; then echo "vnet_id=$VNET_ID" >> $GITHUB_OUTPUT; fi
          if [ -n "$SUBNET_IDS" ]; then echo "subnet_ids=$SUBNET_IDS" >> $GITHUB_OUTPUT; fi
          if [ -n "$RELAY_EP" ]; then echo "vpc_relay_endpoint_id=$RELAY_EP" >> $GITHUB_OUTPUT; fi
          if [ -n "$WS_EP" ]; then echo "vpc_workspace_endpoint_id=$WS_EP" >> $GITHUB_OUTPUT; fi
          if [ -n "$INSTANCE_PROFILE_ID" ]; then echo "instance_profile_id=$INSTANCE_PROFILE_ID" >> $GITHUB_OUTPUT; fi
          if [ -n "$CATALOG_IDS" ] && [ "$CATALOG_IDS" != "null" ]; then echo "catalog_ids=$CATALOG_IDS" >> $GITHUB_OUTPUT; fi
          if [ -n "$SCHEMA_IDS" ] && [ "$SCHEMA_IDS" != "null" ]; then echo "schema_ids=$SCHEMA_IDS" >> $GITHUB_OUTPUT; fi
          if [ -n "$EXT_LOC_IDS" ] && [ "$EXT_LOC_IDS" != "null" ]; then echo "external_location_ids=$EXT_LOC_IDS" >> $GITHUB_OUTPUT; fi
          if [ -n "$VOLUME_IDS" ] && [ "$VOLUME_IDS" != "null" ]; then echo "volume_ids=$VOLUME_IDS" >> $GITHUB_OUTPUT; fi
          if [ -n "$CLUSTER_IDS" ] && [ "$CLUSTER_IDS" != "null" ]; then echo "compute_cluster_ids=$CLUSTER_IDS" >> $GITHUB_OUTPUT; fi
          if [ -n "$SQL_WH_IDS" ] && [ "$SQL_WH_IDS" != "null" ]; then echo "sql_warehouse_ids=$SQL_WH_IDS" >> $GITHUB_OUTPUT; fi
          if [ -n "$SP_IDS" ] && [ "$SP_IDS" != "null" ]; then echo "service_principal_ids=$SP_IDS" >> $GITHUB_OUTPUT; fi


